#' Obtain Intensity dataframe of targeted peaks
#'
#' @param x A list. Output of \code{\link{generateMetapeaks}}, containing
#'   \code{metapeaks} and \code{propagation_selection}.
#' @param pre The pre-processed MSImagingExperiment object generated by
#'   \code{\link{preProcess}}.
#' @param refList Data frame with at minimum columns \code{Name} (character)
#'   and \code{FeatureMass} (numeric). When loaded via \code{readPanel},
#'   also contains \code{OriginalName}.
#' @param mz_threshold An m/z threshold that defines positive association of
#'   the expected m/z value and an actual metapeak m/z location.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{CorrespondenceMatrix}{Data frame mapping observed metapeaks to
#'     expected marker masses, with summary statistics.}
#'   \item{IntensityDF}{Data frame of intensity values (pixels x markers) for
#'     all markers associated with an observed metapeak.}
#'   \item{SpatialCoords}{Data frame of spatial pixel coordinates.}
#'   \item{SummarySpectra}{Data frame of summary spectra (mean and skyline).}
#'   \item{AllMetapeaks}{List with \code{AllMetapeaksIntensity} and
#'     \code{AllMetapeaksCorrespondence} containing all detected metapeaks (targeted and untargeted).}
#'   \item{FilteredDF}{TIC-filtered intensity data frame.}
#' }
#'
#'
#' @importFrom Cardinal mz featureData
#' @importFrom matter colSums rowSums
#' @importFrom dplyr relocate
#' @importFrom stats cor na.omit
#' @export
#'
#' @examples
#' path <- system.file("extdata/Example_data/Example_data.imzML", package = "gutenTAG")
#' panel_path <- system.file("extdata/ref_list.csv", package = "gutenTAG")
#' panel <- readPanel(path = panel_path)
#' raw <- readMSIData(path)
#' pre <- preProcess(raw)
#' peaks <- peakDetection(pre)
#' metapeaks <- generateMetapeaks(peaks, hist_smooth_factor = 1)
#' assignMetapeaks(x = metapeaks, pre, panel)

assignMetapeaks <- function(x, pre, refList, mz_threshold = 1) {

  # validity checks
  .valid.assignMetapeaks(x, pre, refList, mz_threshold)

  # get spatial coordinates and correct if needed
  coords <- as.data.frame(pData(pre))[, c("x","y")]
  coords <- .translate_coordinates(coords)

  # 1. generate the initial correspondence matrix
  initial_correspondence <- .generateCorrespondence(x = x, pre = pre, refList = refList, mz_threshold = mz_threshold)
  # 2. generate the final intensity dataframe
  final_intensity_dataframe <- .generateFinalIntensityDF(x, pre, prev_output = initial_correspondence, refList = refList)
  # 3. add elements to correspondence matrix
  final_correspondence_matrix <- .finaliseCorrespondence(x, pre, refList, prev_output = final_intensity_dataframe)
  # 4. create filtered dataframe
  final_filtered <- .filterTIC(x, prev_output = final_correspondence_matrix)

  # extract for return
  Correspondence <- final_correspondence_matrix$final_correspondence
  Intensity <- final_intensity_dataframe$final_intensity_targeted
  AllMetapeaksIntensity <- final_intensity_dataframe$final_intensity
  AllMetapeaksCorrespondence <- final_correspondence_matrix$untargeted_correspondence

  # order dataframe columns by mz order
  Intensity <- Intensity[, Correspondence$marker]
  final_filtered <- final_filtered[, Correspondence$marker]

  # summary spectra
  summarised_spectra <- .summariseSpectra(pre)

  # values to return
  return(list(CorrespondenceMatrix = Correspondence,
              IntensityDF = Intensity,
              SpatialCoords = coords,
              SummarySpectra = summarised_spectra,
              AllMetapeaks = list(AllMetapeaksIntensity = AllMetapeaksIntensity,
                                  AllMetapeaksCorrespondence = AllMetapeaksCorrespondence),
              FilteredDF = final_filtered,
              params = c(x$params, list(mz_threshold = mz_threshold))))

}

### Hidden functions ###

# function for generating the correspondence matrix
.generateCorrespondence <- function(x, pre, refList, mz_threshold = mz_threshold){

  # extract metepeaks and propagation_selection from x
  mpeaks <- x$metapeaks

  # get m/z vector
  mz_vector <- as.data.frame(mz(pre))

  # Map metapeaks to panel. for each metapeak find nearest reference mass within threshold
  dist_matrix <- abs(outer(mpeaks$max, refList$FeatureMass, "-")) 
  min_dist <- apply(dist_matrix, 1, min)
  mapping_meta_cleaned <- apply(dist_matrix, 1, which.min)
  mapping_meta_cleaned[min_dist > mz_threshold] <- NA
  #construct correspondence matrix
  correspondence_matrix <- data.frame(mz_location = mpeaks$max,
                                      expected_mz_location = refList$FeatureMass[mapping_meta_cleaned],
                                      marker = refList$Name[mapping_meta_cleaned])
  # get NA cols
  was_na <- is.na(correspondence_matrix$marker)
  # rename duplicates
  correspondence_matrix$marker <- make.unique(correspondence_matrix$marker, sep = ".duplicate.")
  correspondence_matrix$marker[was_na] <- NA

  return(list(
    correspondence_matrix = correspondence_matrix,
    metapeaks = mpeaks,
    mz_vector = mz_vector)
  )

}
# function for generating final intensity dataframe
.generateFinalIntensityDF <- function(x, pre, prev_output, refList){

  rownames(refList) <- refList$Name
  # extract raw intensity dataframe from pre-processed data
  raw_intensity <- ProtGenerics::spectra(pre)

  # extract from prev_output
  correspondence <- prev_output$correspondence_matrix
  mz_vector <- prev_output$mz_vector
  metapeaks <- prev_output$metapeaks

  # create untargeted final intensity dataframe
  # raw_intensity is mz_bins x pixels (spectra() convention), so ncol = n_pixels
  n_pixels    <- ncol(raw_intensity)
  n_metapeaks <- nrow(correspondence)
  final_intensity <- matrix(0, nrow = n_pixels, ncol = n_metapeaks)
  eps <- sqrt(.Machine$double.eps)
  for (k in seq_len(n_metapeaks)) {
    # which mz locations are inside the peak (boolean)
    selected_mz_location <- mz_vector$mz >= metapeaks$limits[k, 1] - eps & mz_vector$mz <= metapeaks$limits[k, 2] + eps
    # sum the intensity of the mz locations inside the peak
    final_intensity[, k] <- colSums(raw_intensity[selected_mz_location, , drop = FALSE])
  }

  # get names for metapeak values
  colnames(final_intensity) <- paste0(as.character(round(metapeaks$max, 2)), " m/z")

  # Annotated metapeaks only
  final_intensity_targeted <- final_intensity[, !is.na(correspondence$marker)]
  colnames(final_intensity_targeted) <- correspondence$marker[!is.na(correspondence$marker)]
  final_intensity_targeted <- as.data.frame(final_intensity_targeted)

  # add zero columns for markers that aren't assigned metapeaks
  final_intensity_targeted[setdiff(refList$Name, colnames(final_intensity_targeted))] <- 0
  final_intensity_targeted <- final_intensity_targeted[
    order(match(colnames(final_intensity_targeted), correspondence$marker))
  ]

  return(list(
    final_intensity = final_intensity,
    final_intensity_targeted = final_intensity_targeted,
    metapeaks = metapeaks,
    correspondence = correspondence
  ))

}

# finalise the correspondence matrix
.finaliseCorrespondence <- function(x, pre, refList, prev_output){

  # extract raw intensity dataframe from pre-processed data
  raw_intensity <- ProtGenerics::spectra(pre)

  # extract from previous output
  final_intensity_targeted <- prev_output$final_intensity_targeted
  final_intensity <- prev_output$final_intensity
  correspondence <- prev_output$correspondence
  metapeaks <- prev_output$metapeaks

  # Summary statistics and expand correspondence matrix
  mean_intensity <- colMeans(final_intensity)
  sd_intensity <- apply(final_intensity, MARGIN = 2, FUN = sd)

  # add mean and sd to correspondence matrix
  correspondence$mean <- mean_intensity
  correspondence$sd <- sd_intensity

  # corrected_sd: residuals from mean-variance regression, normalised by sd_intensity
  # this gives a dimensionless score comparable across markers, capturing deviation from
  # the expected mean-variance trend independent of absolute variability
  # note: zero-variance channels will produce Inf/-Inf (sd_intensity == 0); handle upstream
  corrected_sd_model <- lm(log(1 + sd_intensity) ~ log(1 + mean_intensity))
  residuals <- corrected_sd_model$residuals
  correspondence$corrected_sd <- residuals / sd_intensity

  # store metapeak width in correspondence matrix
  correspondence$peak_width <- metapeaks$metapeaks$width

  # total signal of each peak
  total_signal <- colSums(raw_intensity)

  # correlation between each marker's intensity and total raw signal intensity
  total_signal_correlation <- drop(cor(log(final_intensity + 1), log(1 + total_signal)))
  correspondence$total_signal_correlation <- total_signal_correlation^2

  # Remove all un-annotated peaks from correspondence matrix
  correspondence_matrix_targeted <- na.omit(correspondence)
  correspondence_matrix_targeted <- relocate(correspondence_matrix_targeted, "marker")

  # add unobserved markers to the final correspondence matrix so that nrow correspondence matrix = ncol IntensityDF

  # get markers that didn't form metapeaks
  names_to_add <- refList$Name[which(!refList$Name %in% correspondence_matrix_targeted$marker)]
  mass_to_add <- refList$FeatureMass[which(!refList$Name %in% correspondence_matrix_targeted$marker)]

  final_correspondence_matrix <- correspondence_matrix_targeted
  new_row_indices <- seq_along(names_to_add) + nrow(final_correspondence_matrix)
  final_correspondence_matrix[new_row_indices, c("marker", "expected_mz_location")] <- cbind(names_to_add, mass_to_add)
  # convert character to numeric before sorting
  final_correspondence_matrix$expected_mz_location <- as.numeric(final_correspondence_matrix$expected_mz_location)
  # sort by expected mass
  final_correspondence_matrix <- dplyr::arrange(final_correspondence_matrix, expected_mz_location)

  return(list(
    final_correspondence = final_correspondence_matrix,
    final_intensity_targeted = final_intensity_targeted,
    untargeted_correspondence = correspondence
  ))

}


# function for generating filtered intensity dataframe
.filterTIC <- function(x, prev_output){

  final_intensity_targeted <- prev_output$final_intensity_targeted

  # filter on TIC
  tic <- rowSums(final_intensity_targeted)
  # remove NAs
  tic[tic == 0] <- NA
  tic <- na.omit(tic)

  # otsu threshold on TIC
  tic_threshold <- .otsu_thresholding(log10(tic))
  # filter out TIC pixels below threshold
  tic_filtered <- tic[log10(tic) > tic_threshold]

  # set pixels that do not pass filtering to NA
  tic[!tic %in% tic_filtered] <- NA
  # how many are filtered out?
  length(tic[is.na(tic)])

  # which pixels pass filtering
  indices <- which(tic %in% tic_filtered)

  # set all pixels that do not pass the TIC filter to NA across all channels at once
  final_filtered <- as.matrix(final_intensity_targeted)
  final_filtered[-indices, ] <- NA

  # add column names to filtered dataframe
  final_filtered <- data.frame(final_filtered)
  colnames(final_filtered) <- colnames(final_intensity_targeted)

  return(final_filtered = final_filtered)

}


# calculate summary spectra
.summariseSpectra <- function(pre){

  # compute summary spectra
  summarised_spectra <- Cardinal::summarizeFeatures(pre, stat=c(skyline = "max", mean = "mean"))
  summarised_spec <- data.frame(featureData(summarised_spectra))

  return(summarised_spec)
}


