#' Obtain Intensity dataframe of targeted peaks
#'
#' @param x Metapeaks from output of metapeakGeneration function.
#' @param refList A reference list of masses of interest. Should be dataframe with two columns: 'Name' and 'FeatureMass'.
#' @param pre The pre-processed MSImagingExperiment object generated by calling the function preprocess
#' @param mz_threshold An m/z threshold that defines positive association of the expected m/z value and an actual metapeak m/z location.
#'
#' @return List containing a). A dataframe of intensity values for all markers that are associated with an observed metapeak, and b). A dataframe that references metapeaks to expected peaks, aswell as optional additional features. c). A spatial coordinate dataframe for each pixel.
#'
#' @importFrom N2R crossKnn
#' @importFrom Cardinal mz
#' @importFrom matter colSums rowSums
#' @export
#'
#' @examples
#' path <- system.file("extdata/Example_data.imzML", package = "maldipackage")
#' panel_path <- system.file("extdata/ref_list.csv", package = "maldipackage")
#' panel <- readPanel(path = panel_path)
#' raw <- readMSIData(path)
#' pre <- preProcess(raw, cores = 2)
#' peaks <- peakDetection(pre, core = 2)
#' metapeaks <- generateMetapeaks(peaks)
#' assignMetapeaks(x = metapeaks, pre, panel)

assignMetapeaks <- function(x, pre, refList, mz_threshold = 1) {

  # validity checks
  #.valid.assignMetapeaks(x, pre, refList, mz_threshold)

  # get spatial coordinates and correct if needed
  coords <- as.data.frame(pData(pre))[, c("x","y")]
  coords <- .correctCoordinates(coords)

  # 1. generate the initial correspondence matrix
  initial_correspondence <- .generateCorrespondence(x, pre, refList, mz_threshold = mz_threshold)
  # 2. generate the final intensity dataframe
  final_intensity_dataframe <- .generateFinalIntensityDF(x, pre, prev_output = initial_correspondence)
  # 3. add elements to correspondence matrix
  final_correspondence_matrix <- .finaliseCorrespondence(x, pre, refList, prev_output = final_intensity_dataframe)
  # 4. create filtered dataframe
  final_filtered <- .filterTIC(x, prev_output = final_correspondence_matrix)

  # extract for return
  Correspondence <- final_correspondence_matrix$final_correspondence
  Intensity <- final_intensity_dataframe$final_intensity_targeted
  UntargetedDF <- final_intensity_dataframe$final_intensity
  UntargetedCorrespondence <- initial_correspondence$correspondence_matrix

  # values to return
  return(list(CorrespondenceMatrix = Correspondence,
              IntensityDF = Intensity,
              SpatialCoords = coords,
              Untargeted = list(UntargetedIntensity = UntargetedDF,
                                UntargetedCorrespondence = UntargetedCorrespondence),
              FilteredDF = final_filtered))

}

### Hidden functions ###

# function for generating the correspondence matrix
.generateCorrespondence <- function(x, pre, refList, mz_threshold = mz_threshold){

  # extract metepeaks and propagation_selection from x
  metapeaks <- x$metapeaks

  # Map metapeaks to panel
  mapping_meta <- N2R::crossKnn(mA = matrix(metapeaks$max),
                                mB = matrix(refList$FeatureMass, ncol = 1), k = 10, indexType = "L2", verbose = FALSE)

  # remove all mappings below the m/z distance association threshold
  mapping_meta[mapping_meta > mz_threshold] <- 0
  mapping_meta_cleaned <- apply(as.matrix(mapping_meta), MARGIN = 2, FUN = .which_max_modified)
  #construct correspondence matrix
  correspondence_matrix <- data.frame(mz_location = metapeaks$max,
                                      expected_mz_location = refList$FeatureMass[mapping_meta_cleaned],
                                      marker = refList$Name[mapping_meta_cleaned])
  # get NA cols
  was_na <- is.na(correspondence_matrix$marker)
  # rename duplicates
  correspondence_matrix$marker <- make.unique(correspondence_matrix$marker, sep = ".duplicate.")
  correspondence_matrix$marker[was_na] <- NA

  return(list(
    correspondence_matrix = correspondence_matrix,
    metapeaks = metapeaks,
    mz_vector = mz_vector)
  )

}

# function for generating final intensity dataframe
.generateFinalIntensityDF <- function(x, pre, prev_output){

  rownames(refList) <- refList$Name
  # extract raw intensity dataframe from pre-processed data
  raw_intensity <- iData(pre)

  # extract from prev_output
  correspondence <- prev_output$correspondence_matrix
  mz_vector <- prev_output$mz_vector
  metapeaks <- prev_output$metapeaks

  # create untargeted final intensity dataframe
  final_intensity <- c()
  eps <- sqrt(.Machine$double.eps)
  for (k in seq_len(nrow(correspondence))) {
    # which mz locations are inside the peak (boolean)
    selected_mz_location <- mz_vector$mz >= metapeaks$limits[k, 1] - eps & mz_vector$mz <= metapeaks$limits[k, 2] + eps
    # sum the intensity of the mz locations inside the peak
    intensity_temp <- colSums(raw_intensity[selected_mz_location, , drop = FALSE])
    final_intensity <- cbind(final_intensity, intensity_temp)
  }

  # get names for metapeak values
  colnames(final_intensity) <- paste0(as.character(round(metapeaks$center, 2)), " m/z")

  # Annotated metapeaks only
  final_intensity_targeted <- final_intensity[, !is.na(correspondence$marker)]
  colnames(final_intensity_targeted) <- correspondence$marker[!is.na(correspondence$marker)]
  final_intensity_targeted <- as.data.frame(final_intensity_targeted)

  # add zero columns for markers that aren't assigned metapeaks
  final_intensity_targeted[setdiff(refList$Name, colnames(final_intensity_targeted))] <- 0
  final_intensity_targeted <- final_intensity_targeted[
    order(match(colnames(final_intensity_targeted), correspondence$marker))
  ]

  return(list(
    final_intensity = final_intensity,
    final_intensity_targeted = final_intensity_targeted,
    metapeaks = metapeaks,
    correspondence = correspondence
  ))

}

# finalise the correspondence matrix
.finaliseCorrespondence <- function(x, pre, refList, prev_output){

  # extract raw intensity dataframe from pre-processed data
  raw_intensity <- iData(pre)

  # extract from previous output
  final_intensity_targeted <- prev_output$final_intensity_targeted
  final_intensity <- prev_output$final_intensity
  correspondence <- prev_output$correspondence
  metapeaks <- prev_output$metapeaks

  # Summary statistics and expand correspondence matrix
  mean_intensity <- colMeans(final_intensity)
  sd_intensity <- apply(final_intensity, MARGIN = 2, FUN = sd)

  # add mean and sd to correspondence matrix
  correspondence$mean <- mean_intensity
  correspondence$sd <- sd_intensity

  # set corrected sd as the ratio between the residuals (plus sd) and the sd
  corrected_sd <- lm(log(1 + sd_intensity) ~ log(1 + mean_intensity))
  residuals <- corrected_sd$residuals
  correspondence$corrected_sd <- residuals + sd_intensity / sd_intensity
  # former definition: correspondence_matrix$corrected_sd <- corrected_sd$residuals

  # store metapeak width in correspondence matrix
  correspondence$peak_width <- metapeaks$metapeaks$width

  # total signal of each peak
  total_signal <- colSums(raw_intensity)

  # correlation between the marker intensity and total raw signal intensity
  total_signal_correlation <- apply(final_intensity, MARGIN = 2, FUN = function(x) {cor(log(x + 1), log(1 + total_signal))})
  correspondence$total_signal_correlation <- total_signal_correlation^2

  # Remove all un-annotated peaks from correspondence matrix
  correspondence_matrix_targeted <- na.omit(correspondence)
  correspondence_matrix_targeted <- relocate(correspondence_matrix_targeted, "marker")

  # add unobserved markers to the final correspondence matrix so that nrow correspondence matrix = ncol IntensityDF

  # get markers that didn't form metapeaks
  names_to_add <- refList$Name[which(!refList$Name %in% correspondence_matrix_targeted$marker)]
  mass_to_add <- refList$FeatureMass[which(!refList$Name %in% correspondence_matrix_targeted$marker)]

  final_correspondence_matrix <- correspondence_matrix_targeted
  new_row_indices <- seq_along(names_to_add) + nrow(final_correspondence_matrix)
  final_correspondence_matrix[new_row_indices, c("marker", "expected_mz_location")] <- cbind(names_to_add, mass_to_add)
  # sort by expected mass
  final_correspondence_matrix <- dplyr::arrange(final_correspondence_matrix, expected_mz_location)

  return(list(
    final_correspondence = final_correspondence_matrix,
    final_intensity_targeted = final_intensity_targeted
  ))

}


# function for generating filtered intensity dataframe
.filterTIC <- function(x, prev_output){

  final_intensity_targeted <- final_correspondence_matrix$final_intensity_targeted

  # filter on TIC
  tic <- rowSums(final_intensity_targeted)
  # remove NAs
  tic[tic == 0] <- NA
  tic <- na.omit(tic)

  # otsu threshold on TIC
  tic_threshold <- .otsu_thresholding(log10(tic))
  # filter out TIC pixels below threshold
  tic_filtered <- tic[log10(tic) > tic_threshold]

  # set pixels that do not pass filtering to NA
  tic[!tic %in% tic_filtered] <- NA
  # how many are filtered out?
  length(tic[is.na(tic)])

  # which pixels pass filtering
  indices <- which(tic %in% tic_filtered)

  # create zero matrix with correct dims
  final_filtered <- matrix(NA, nrow = nrow(final_intensity_targeted), ncol = ncol(final_intensity_targeted))
  for (j in 1:ncol(final_intensity_targeted)){

    channel <- final_intensity_targeted[,j]

    # pixel values pass filter
    filtered_vals <- channel[indices]
    channel[!channel %in% filtered_vals] <- NA
    final_filtered[,j] <- channel

  }

  # add column names to filtered dataframe
  final_filtered <- data.frame(final_filtered)
  colnames(final_filtered) <- colnames(final_intensity_targeted)

  return(final_filtered = final_filtered)

}

