#' Obtain Intensity dataframe of targeted peaks
#'
#' @param x Metapeaks from output of metapeakGeneration function.
#' @param refList A reference list of masses of interest. Should be dataframe with two columns: 'Name' and 'FeatureMass'.
#' @param pre The pre-processed MSImagingExperiment object generated by calling the function preprocess
#' @param mz_threshold An m/z threshold that defines positive association of the expected m/z value and an actual metapeak m/z location.
#'
#' @return List containing a). A dataframe of intensity values for all markers that are associated with an observed metapeak, and b). A dataframe that references metapeaks to expected peaks, aswell as optional additional features. c). A spatial coordinate dataframe for each pixel.
#'
#' @importFrom N2R crossKnn
#' @export
#'
#' @examples
#' assignMetapeaks(metapeaks, peakAnnotation, peakPre)

assignMetapeaks <- function(x, pre, refList, mz_threshold = 1){

  # validity checks
  .valid.assignMetapeaks(x, pre, refList, mz_threshold)

  # get variables from pre-processed object
  mz_vector <- as.data.frame(mz(pre))
  colnames(mz_vector) <- "mz"
  raw_intensity <- iData(pre)

  # get spatial coordinates and correct if needed
  coords <- as.data.frame(pData(pre))[, c("x","y")]
  coords <- .correctCoordinates(coords)

  # extract metepeaks and propagation_selection from x
  x <- x$metapeaks

  # Map metapeaks to panel
  mapping_meta <- N2R::crossKnn(mA = matrix(x$max),
                                mB= matrix(refList$FeatureMass, ncol = 1), k = 10, indexType = "L2", verbose = FALSE) ## change to k = 1??

  # remove all mappings below the m/z distance association threshold
  mapping_meta[mapping_meta > mz_threshold] <- 0
  mapping_meta_cleaned <- apply(as.matrix(mapping_meta), MARGIN = 2, FUN = .which_max_modified)

  correspondence_matrix <- data.frame(mz_location = x$max,
                                      expected_mz_location = refList$FeatureMass[mapping_meta_cleaned],
                                      marker = refList$Name[mapping_meta_cleaned])

  rownames(refList) <- refList$Name

  final_intensity <- c()
  for (k in 1:nrow(correspondence_matrix)) {
    # which mz locations are inside the peak (boolean)
    selected_mz_location <- mz_vector$mz >= x$limits[k,1] & mz_vector$mz <= x$limits[k,2]
    # those mz values
    mz_vector$mz[which(selected_mz_location == TRUE)]
    if (sum(selected_mz_location) > 1) {
      intensity_temp = colSums(raw_intensity[selected_mz_location, ])
    }
    # if there is only one mz location, the intensity list is only the intensity values of the one mz location
    if (sum(selected_mz_location) == 1) {
      intensity_temp <- (raw_intensity[selected_mz_location, ])
    }
    #intensity_temp = Correspondence_matrix$Annotation_peaks[k]
    final_intensity <- cbind(final_intensity, intensity_temp)

  }

  # Summary statistics and expand correspondence matrix
  mean_intensity <- colMeans(final_intensity)
  sd_intensity <- apply(final_intensity, MARGIN = 2, FUN = sd)

  # add mean and sd to correspondence matrix
  correspondence_matrix$mean <- mean_intensity
  correspondence_matrix$sd <- sd_intensity

  # set corrected sd as the ratio between the residuals (plus sd) and the sd
  corrected_sd <- lm(log(1+sd_intensity) ~ log(1+mean_intensity))
  residuals <- corrected_sd$residuals
  correspondence_matrix$corrected_sd <- residuals + sd_intensity / sd_intensity
  # former definition: correspondence_matrix$corrected_sd <- corrected_sd$residuals

  correspondence_matrix$peak_width <- x$metapeaks$width

  # Total signal of each peak
  total_signal <- colSums(raw_intensity)

  # correlation between the marker intensity and total raw signal intensity
  total_signal_correlation <- apply(final_intensity, MARGIN = 2, FUN = function(x) {cor(log(x + 1), log(1 + total_signal))})
  correspondence_matrix$total_signal_correlation <- total_signal_correlation^2


  # Annotated metapeaks only
  final_intensity_targeted <- final_intensity[, !is.na(correspondence_matrix$marker)]
  colnames(final_intensity_targeted) <- correspondence_matrix$marker[!is.na(correspondence_matrix$marker)]
  final_intensity_targeted <- as.data.frame(final_intensity_targeted)


  # add zero columns for markers that aren't assigned metapeaks
  zeros_df <- data.frame(matrix(0, nrow = length(final_intensity_targeted[, 1]), ncol = length(refList$Name)))
  colnames(zeros_df) <- refList$Name
  cols_to_enter <- which(colnames(zeros_df) %in% colnames(final_intensity_targeted))
  zeros_df[cols_to_enter] <- final_intensity_targeted

  # update final_intensity_targeted with the new df containing zeros for channels that aren't picked up
  final_intensity_targeted <- zeros_df


  # Remove all un-annotated peaks from correspondence matrix
  correspondence_matrix_targeted <- na.omit(correspondence_matrix)
  correspondence_matrix_targeted <- relocate(correspondence_matrix_targeted, "marker")


  # filter on TIC

  tic <- rowSums(final_intensity_targeted)
  # remove NAs
  tic[tic == 0] <- NA
  tic <- na.omit(tic)

  # otsu threshold on TIC
  tic_threshold = .otsu_thresholding(log10(tic))
  # filter out TIC pixels below threshold
  tic_filtered <- tic[log10(tic) > tic_threshold]

  # set pixels that do not pass filtering to NA
  tic[!tic %in% tic_filtered] <- NA
  # how many are filtered out?
  length(tic[is.na(tic)])

  # which pixels pass filtering
  indices <- which(tic %in% tic_filtered)

  # create zero matrix with correct dims
  final_filtered <- matrix(NA, nrow = nrow(final_intensity_targeted), ncol = ncol(final_intensity_targeted))
  for (j in 1:ncol(final_intensity_targeted)){

    channel <- final_intensity_targeted[,j]

    # pixel values pass filter
    filtered_vals <- channel[indices]
    channel[!channel %in% filtered_vals] <- NA
    final_filtered[,j] <- channel

  }

  # add column names to filtered dataframe
  final_filtered <- data.frame(final_filtered)
  colnames(final_filtered) <- colnames(final_intensity_targeted)

  # potentially change the columns with 0's to NA's

  return(list(CorrespondenceMatrix = correspondence_matrix_targeted,
              IntensityDF = final_intensity_targeted,
              SpatialCoords = coords,
              Untargeted = list(UntargetedIntensity = final_intensity,
                                UntargetedCorrespondence = correspondence_matrix),
              FilteredDF = final_filtered))

}
