#' Obtain Intensity dataframe of targeted peaks/
#'
#' @param x Metapeaks from output of metapeakGeneration function.
#' @param refList A reference list of masses of interest. Should be dataframe with two columns: 'Name' and 'FeatureMass'.
#' @param pre The pre-processed MSImagingExperiment object generated by calling the function preprocess
#' @param mz_threshold An m/z threshold that defines positive association of the expected m/z value and an actual metapeak m/z location.
#'
#' @return List containing a). A dataframe of intensity values for all markers that are associated with an observed metapeak, and b). A dataframe that references metapeaks to expected peaks, aswell as optional additional features. c). A spatial coordinate dataframe for each pixel.
#' @export
#'
#' @examples
#' getIntensityDF(metapeaks, peakAnnotation, peakPre)

getIntensityDF <- function(x, pre, refList, mz_threshold = 1){

  # get variables from pre-processed object
  mz_vector <- as.data.frame(mz(pre))
  colnames(mz_vector) <- "mz"
  raw_intensity <- iData(pre)

  # get spatial coordinates and correct if needed
  coords <- as.data.frame(pData(pre))[, c("x","y")]
  coords <- .correctCoordinates(coords)


  # extract metepeaks and propagation_selection from x
  x <- x$metapeaks
  propagation_selection <- x$propagation_selection

  # Map metapeaks to panel
  mapping_meta <- N2R::crossKnn(mA = matrix(x$max),
                           mB= matrix(refList$FeatureMass, ncol = 1), k = 10, indexType = "L2", verbose = FALSE)

  # remove all mappings below the m/z distance association threshold
  mapping_meta[mapping_meta > mz_threshold] <- 0
  mapping_meta_cleaned <- apply(as.matrix(mapping_meta), MARGIN = 2, FUN = .which_max_modified)

  associated_marker <- c()
  for (k in 1:length(x$max)) {
    selected_mz_location <- range(mz_vector$mz[as.numeric(propagation_selection) == k])
    annotation_assigned <- refList$Name[refList$FeatureMass > selected_mz_location[1] & refList$FeatureMass < selected_mz_location[2]]
    if (length(annotation_assigned) == 0){
      annotation_assigned = NA
    }
    if (length(annotation_assigned) > 1){
      annotation_assigned = paste(annotation_assigned, collapse="__OR__")
    }
    associated_marker <- c(associated_marker, annotation_assigned)
  }

  correspondence_matrix <- data.frame(mz_location = x$max,
                                      expected_mz_location = refList$FeatureMass[mapping_meta_cleaned],
                                      marker = refList$Name[mapping_meta_cleaned])



  rownames(refList) <- refList$Name


  final_intensity <- c()
  for (k in 1:nrow(correspondence_matrix)) {
    # which mz locations are inside the peak (boolean)
    selected_mz_location <- mz_vector$mz >= x$limits[k,1] & mz_vector$mz <= x$limits[k,2]
    # those mz values
    mz_vector$mz[which(selected_mz_location == TRUE)]
    if (sum(selected_mz_location) > 1) {
      intensity_temp = colSums(raw_intensity[selected_mz_location, ])
    }
    # if there is only one mz location, the intensity list is only the intensity values of the one mz location
    if (sum(selected_mz_location) == 1) {
      intensity_temp <- (raw_intensity[selected_mz_location, ])
    }
    #intensity_temp = Correspondence_matrix$Annotation_peaks[k]
    final_intensity <- cbind(final_intensity, intensity_temp)

  }

  # Summary statistics and expand correspondence matrix
  mean_intensity <- colMeans(final_intensity)
  sd_intensity <- apply(final_intensity, MARGIN = 2, FUN = sd)
  corrected_sd <- lm(log(sd_intensity) ~ log(mean_intensity))

  correspondence_matrix$corrected_sd <- corrected_sd$residuals
  correspondence_matrix$peak_width <- x$metapeaks$width

  # Total signal of each peak
  total_signal <- colSums(raw_intensity)

  # correlation between the marker intensity and total raw signal intensity
  total_signal_correlation <- apply(final_intensity, MARGIN = 2, FUN = function(x) {cor(log(x + 1), log(1 + total_signal))})
  correspondence_matrix$total_signal_correlation <- total_signal_correlation^2


  # Annotated metapeaks only
  final_intensity_targeted <- final_intensity[, !is.na(correspondence_matrix$marker)]
  colnames(final_intensity_targeted) <- correspondence_matrix$marker[!is.na(correspondence_matrix$marker)]
  final_intensity_targeted <- as.data.frame(final_intensity_targeted)

  # Remove all u-nannotated peaks from correspondence matrix
  correspondence_matrix_targeted <- na.omit(correspondence_matrix)
  correspondence_matrix_targeted <- relocate(correspondence_matrix_targeted, "marker")

  return(list(CorrespondenceMatrix = correspondence_matrix_targeted,
              IntensityDF = final_intensity_targeted,
              SpatialCoords = coords,
              Untargeted = list(UntargetedIntensity = final_intensity,
                                UntargetedCorrespondence = correspondence_matrix)))

}
