#' Pre-processing
#'
#' Performs pre-processing steps on a raw MSImagingExperiment object. Steps include normalisation, spectral smoothing and baseline reduction.
#'
#' @param x An unprocessed (raw) MSImagingExperiment object. Can be generated by loading in a .imzML file using Cardinal "readMSIData" function.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object
#'   controlling parallel execution. Defaults to
#'   \code{\link[BiocParallel]{bpparam}()}, which uses the session-wide
#'   registered backend. Use \code{BiocParallel::MulticoreParam(n)} on
#'   Linux/macOS or \code{BiocParallel::SnowParam(n)} on Windows for
#'   multi-core processing.
#' @returns A pre-processed MSImagingExperiment object.
#'
#' @rawNamespace import(Cardinal, except = peaks)
#' @importClassesFrom BiocParallel BiocParallelParam
#'
#' @export
#' @examples
#' path <- system.file("extdata/Example_data.imzML", package = "gutenTAG")
#' panel_path <- system.file("extdata/ref_list.csv", package = "gutenTAG")
#' panel <- readPanel(path = panel_path)
#' raw <- readMSIData(path)
#' preProcess(raw)

preProcess <- function(x, BPPARAM = BiocParallel::bpparam()){

  # validity checks for preProcess
  .valid.preProcess(x, BPPARAM)

  x |>
    Cardinal::normalize(method = "tic") |>
    Cardinal::smooth(method = "gaussian") |>
    Cardinal::reduceBaseline(method = "locmin") |>
    Cardinal::process(BPPARAM = BPPARAM)

}

