#' Pre-processing
#'
#' Performs pre-processing steps on a raw MSImagingExperiment object. Steps include normalisation, spectral smoothing and baseline reduction.
#'
#' @param x An unprocessed (raw) MSImagingExperiment object. Can be generated by loading in a .imzML file using Cardinal "readMSIData" function.
#' @param cores The number of cores to be used for processing.
#' @returns A pre-processed MSImagingExperiment object.
#'
#' @rawNamespace import(Cardinal, except = peaks)
#' @import BiocParallel
#' @export
#' @examples
#' preProcess(rawFile, 4)


preProcess <- function(x, cores){

  x %>%
    Cardinal::normalize(method = "tic") %>%
    smoothSignal(method = "gaussian", plot=FALSE) %>%
    reduceBaseline(method="locmin") %>%
    process(BPPARAM = MulticoreParam(workers = cores))

}

