#' Pre-processing
#'
#' Performs pre-processing steps on a raw MSImagingExperiment object. Steps include normalisation, spectral smoothing and baseline reduction.
#'
#' @param x An unprocessed (raw) MSImagingExperiment object. Can be generated by loading in a .imzML file using Cardinal "readMSIData" function.
#' @param cores The number of cores to be used for processing.
#' @returns A pre-processed MSImagingExperiment object.
#'
#' @rawNamespace import(Cardinal, except = peaks)
#' @import BiocParallel
#' @import BiocStyle
#'
#' @export
#' @examples
#' path <- system.file("extdata/Example_data.imzML", package = "gutenTAG")
#' panel_path <- system.file("extdata/ref_list.csv", package = "gutenTAG")
#' panel <- readPanel(path = panel_path)
#' raw <- readMSIData(path)
#' preProcess(raw, 2)
preProcess <- function(x, cores) {
  # validity checks for preProcess
  .valid.preProcess(x, cores)

  x |>
    Cardinal::normalize(method = "tic") |>
    Cardinal::smooth(method = "gaussian") |>
    Cardinal::reduceBaseline(method = "locmin") |>
    Cardinal::process(BPPARAM = BiocParallel::MulticoreParam(workers = cores))
}
